app:
  name: eth-exporter
  log: "/var/log/eth-exporter"
  port: "9119"

  instance:
    ip: "10.4.2.135"
    device: "eth0"

  db:
    token: "ZBQbf0tUGAvL54dTjWPnWg-92yDjk6XyCmFg4ytWD_jm8EsSqU3xwAGunKXP4naxKI4eJ2so_Hta-Z5hJtMJGQ=="
    url: "http://10.4.2.135:8086"
    bucket: "amrom"
    org: "amrom"
